services:
  web:
    build: .
    entrypoint: sh -c "uv sync --group dev --group test; DEBUG=1 exec ./manage.py runserver 0.0.0.0:9000"
    container_name: django_web
    environment:
      - SECRET_KEY
      - DATABASE_URL=${DATABASE_URL-}
      - REDIS_URL=${REDIS_URL-redis://redis:6379}
      - NTA_API_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - PYTHONWARNINGS=all
      - EMAIL_HOST
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - TFL_APP_ID
      - TFL_APP_KEY
      - NEW_VEHICLE_WEBHOOK_URL
      - TURNSTILE_SITEKEY
      - TURNSTILE_SECRET
      - DEBUG
    volumes:
      - .:/app
    ports:
      - "9000:9000"
      - "35729:35729"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  redis:
    image: redis
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
    mem_limit: 12288m
    command: [
      "redis-server",
      "--maxmemory", "11gb",
      "--maxmemory-policy", "allkeys-lru"
    ]
